name: Build (osx, all haxe versions)

on: [push, repository_dispatch]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]
        haxe-version: [3.4.4, 4.0.3]

    steps:
    - uses: actions/checkout@v1
    - uses: haxeui/haxeui-core/.github/actions/haxe@master
      with:
        haxe-version: ${{ matrix.haxe-version }}

    - name: Setup app (haxe ${{ matrix.haxe-version }}, ${{ matrix.os }})
      run: |
        wget https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.3/wxWidgets-3.1.3.tar.bz2
        tar xjf wxWidgets-3.1.3.tar.bz2
        cd wxWidgets-3.1.3
        ./configure --with-opengl --disable-shared > log.txt
        sudo make
        sudo make install
        echo ::add-path::$(pwd)
        cd ..
        haxelib install hxcpp --always --quiet
        haxelib install hscript --always --quiet

        git clone --branch master https://github.com/haxeui/haxeui-core.git --depth=1
        haxelib dev haxeui-core haxeui-core

        git clone --branch master https://github.com/haxeui/hxWidgets.git --depth=1
        haxelib dev hxWidgets hxWidgets

        haxelib dev haxeui-hxwidgets .

    - name: Build app (haxe ${{ matrix.haxe-version }}, ${{ matrix.os }})
      run: |
        haxe build.hxml
