name: OSX

on: [push, repository_dispatch]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]
        haxe-version: [3.4.7, 4.0.5, 4.1.5, 4.2.2]

    steps:
    - uses: actions/checkout@v1
    - name: Setup Haxe (haxe ${{ matrix.haxe-version }}, ${{ matrix.os }})
      uses: krdlab/setup-haxe@v1
      with:
        haxe-version: ${{ matrix.haxe-version }}

    - name: Setup app (haxe ${{ matrix.haxe-version }}, ${{ matrix.os }})
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      run: |
        wget https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.3/wxWidgets-3.1.3.tar.bz2
        tar xjf wxWidgets-3.1.3.tar.bz2
        cd wxWidgets-3.1.3
        cp ../.github/workflows/include/wx/osx/setup.h include/wx/osx/setup.h 
        ./configure --with-opengl --disable-shared --without-libjpeg > log.txt
        cp ../.github/workflows/include/wx/osx/setup.h include/wx/osx/setup.h 
        make -j4
        make install
        echo ::add-path::$(pwd)
        cd ..
        haxelib install hxcpp --always --quiet
        haxelib install hscript --always --quiet

        git clone --branch master https://github.com/haxeui/haxeui-core.git --depth=1
        haxelib dev haxeui-core haxeui-core

        git clone --branch master https://github.com/haxeui/hxWidgets.git --depth=1
        haxelib dev hxWidgets hxWidgets

        haxelib dev haxeui-hxwidgets .

    - name: Build app (haxe ${{ matrix.haxe-version }}, ${{ matrix.os }})
      run: |
        haxe build.hxml
